### PR TITLE
Add a more informative introduction to readme and show help by argument

### PR DESCRIPTION
**Pull request by vsoch**
hey @bimlas this is a cool tool! The pull request here has some small changes to do the following:

 - adding a simple getting started example to the readme. You show something of this nature in the asciinema, but I think many users will like having something to copy paste.
 - added a help flag. It's very likely a user might add it, forget about it, and then have no clue how to use or where it came from. This way, if he/she tries `--help` the --help output will be printed.
 - Making bin/mosh executable, so the user doesn't need to do it (GitHub should store this).

I tried running mosh, running a command, and then a return code and it echoed 0 (as I expected for list). I'm wondering if there is a way to:

 1. exit the interactive terminal without Control +c, and then have the return code after exit be representative if all of the commands were successful or failed?
 2. Run mosh non interactively? 

If the answer to 2 is no, then it maybe isn't logical to have 1. I'm thinking of the case where I might want to have mosh set up to run some regularly scheduled task, and I wouldn't want interactive, and I'd also want a return code for the group.

Thanks for putting this together! Also, I'm vsoch on reddit in case it wasn't obvious (I think it probably is :P)

### CODE REVIEW

**Comment by bimlas** [comment]
Thank you for your contribution! I'm glad you like the program.

> adding a simple getting started example to the readme. You show something of this nature in the asciinema, but I think many users will like having something to copy paste.

Forgive me, but I don't see that your introduction gives more information than the description of `run` command. In fact, it is not possible to give an "example code" because directory names are mostly different on systems. The code that you wrote only works on your system because those files only exist on your system. Although it would be good, but I don't have an example that would work on every system. Perhaps the system files could somehow be used (`/proc`), but I don't know exactly how.

> exit the interactive terminal without Control +c, and then have the return code after exit be representative if all of the commands were successful or failed?

It is possible and I will implement this. Thanks for the idea! 

> Run mosh non interactively?

Already possible, but forgot to mention in readme:

```bash
$ echo "ls -all" | mosh run "@my-dirs"
```

**Comment by vsoch** [comment]
> Forgive me, but I don't see that your introduction gives more information than the description of run command. In fact, it is not possible to give an "example code" because directory names are mostly different on systems. The code that you wrote only works on your system because those files only exist on your system. Although it would be good, but I don't have an example that would work on every system. Perhaps the system files could somehow be used (/proc), but I don't know exactly how.

That's why I went to /tmp (available on most systems with a shell) and did a general list for whatever folders are there.

What changes would you like to finish the PR?

**Comment by bimlas** [comment]
I've modified readme to make it more readable. If you agree with these (and optionally correct my English grammar errors :smile: ), then I'll merge.

**Comment by bimlas** [comment]
Instead of `/tmp`, I use `/usr/share` in the example, because, for example, on a Vagrant box, `/tmp` is almost empty, whereas `/usr/share` contains directories on Vagrant and Git-for-Windows as well.

**Comment by vsoch** [comment]
It looks great! The intro is samples are much better to introduce the concepts to the user. I did test but assume you did, so ready for merge from my opinion.

**Comment by vsoch** [comment]
Thanks again, had a lot of fun! See you on reddit!

**Comment by bimlas** [comment]
Thanks for your contribution, the documentation looks better now.

I see you have a lot of followers. If you really like the program, would you be kind to star to let others know about it? :smirk:

**Pull request merged**
